version: 0.0
os: linux
files:
  - source: /
    destination: /srv/www/api.invitory.com/deploy/
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/afterinstall
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/applicationstart
      timeout: 300
      runas: ec2-user